### ISSUE TITLE
generically-0.1.1 doesn't permit GHC-9.10

### ISSUE THREAD

**Issue by ysangkok** [haskell-compat/generically#5]
GHC 9.10 uses base-4.20, which is excluded currently by the bounds on hackage: https://hackage.haskell.org/package/generically

**Comment by RyanGlScott** [comment]
My apologies for forgetting to do this! I've raised the upper version bounds in 200ab7f3d8ca5d574eb446b778448acea577e064, and I've applied a corresponding Hackage revision at https://hackage.haskell.org/package/generically-0.1.1/revisions/.
